### ISSUE TITLE
Error when put into replit

### ISSUE THREAD

**Issue by helloguysnot** [Dulanjali-Senarathna/cinemx#1]
i import this project into replit, and i select the programming language as node.js, after it finish cloning it, i typed in the shell: npm install. and it shows up like this.
![image](https://github.com/DulanjaliSenarathna/cinemx/assets/145958352/ec1f87d7-8940-4603-93f0-6b6cd65dceb6)
and i type: npm run dev and its like this: 
![image](https://github.com/DulanjaliSenarathna/cinemx/assets/145958352/d099b62e-6d66-43b8-abc1-f7ddcb395cec)
and i thought its ok so i press run: and this is what i saw:
![image](https://github.com/DulanjaliSenarathna/cinemx/assets/145958352/51d2f412-12ba-44f4-8b7b-0dfdc6a17260)
Whats wrong?

**Comment by DulanjaliSenarathna** [comment]
Please select React Javascript as language in replit. It will be solve the issue.

**Comment by helloguysnot** [comment]
thank you much, I will try
